//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lenguage {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal res() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lenguage.res", typeof(res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actual Balance.
        /// </summary>
        public static string actualbalance {
            get {
                return ResourceManager.GetString("actualbalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Amount.
        /// </summary>
        public static string amount {
            get {
                return ResourceManager.GetString("amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apply.
        /// </summary>
        public static string apply {
            get {
                return ResourceManager.GetString("apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Balanace.
        /// </summary>
        public static string balance {
            get {
                return ResourceManager.GetString("balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Calculator.
        /// </summary>
        public static string calculator {
            get {
                return ResourceManager.GetString("calculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cellphone.
        /// </summary>
        public static string cellphone {
            get {
                return ResourceManager.GetString("cellphone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log out .
        /// </summary>
        public static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to log out?.
        /// </summary>
        public static string closemessage {
            get {
                return ResourceManager.GetString("closemessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Deposit.
        /// </summary>
        public static string deposit {
            get {
                return ResourceManager.GetString("deposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a deposits.
        /// </summary>
        public static string deposits {
            get {
                return ResourceManager.GetString("deposits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DNI.
        /// </summary>
        public static string dni {
            get {
                return ResourceManager.GetString("dni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a the deposit was not made correctly.
        /// </summary>
        public static string dnotok {
            get {
                return ResourceManager.GetString("dnotok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a the deposit was successful.
        /// </summary>
        public static string dok {
            get {
                return ResourceManager.GetString("dok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Home.
        /// </summary>
        public static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Complete the fields well.
        /// </summary>
        public static string log1 {
            get {
                return ResourceManager.GetString("log1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Incorrect username or password.
        /// </summary>
        public static string log2 {
            get {
                return ResourceManager.GetString("log2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Logout.
        /// </summary>
        public static string logOut {
            get {
                return ResourceManager.GetString("logOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Last Name.
        /// </summary>
        public static string lstName {
            get {
                return ResourceManager.GetString("lstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        public static string pasword {
            get {
                return ResourceManager.GetString("pasword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Register.
        /// </summary>
        public static string register {
            get {
                return ResourceManager.GetString("register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failed to register user, please enter another password.
        /// </summary>
        public static string rnotok {
            get {
                return ResourceManager.GetString("rnotok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registered user successfully.
        /// </summary>
        public static string rok {
            get {
                return ResourceManager.GetString("rok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a data saved locally, click apply to save to database.
        /// </summary>
        public static string saveone {
            get {
                return ResourceManager.GetString("saveone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a data stored in the database.
        /// </summary>
        public static string savetwo {
            get {
                return ResourceManager.GetString("savetwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SignIn.
        /// </summary>
        public static string signin {
            get {
                return ResourceManager.GetString("signin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a issued transfers.
        /// </summary>
        public static string tbe {
            get {
                return ResourceManager.GetString("tbe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a the transfer was not successful.
        /// </summary>
        public static string tbnotok {
            get {
                return ResourceManager.GetString("tbnotok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a the transfer was successful.
        /// </summary>
        public static string tbok {
            get {
                return ResourceManager.GetString("tbok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a received transfers.
        /// </summary>
        public static string tbr {
            get {
                return ResourceManager.GetString("tbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transfer.
        /// </summary>
        public static string transfer {
            get {
                return ResourceManager.GetString("transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transference.
        /// </summary>
        public static string transference {
            get {
                return ResourceManager.GetString("transference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User Name.
        /// </summary>
        public static string usr {
            get {
                return ResourceManager.GetString("usr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User Settings.
        /// </summary>
        public static string usrSettings {
            get {
                return ResourceManager.GetString("usrSettings", resourceCulture);
            }
        }
    }
}
